### ISSUE TITLE
MMM-RemoteControl: HTMLElement is not defined

### ISSUE THREAD

**Issue by y0m1g** [MMRIZE/MMM-CalendarExt3#89]
Hello! I believe there's an incompatibility with [`MMM-RemoteControl`](https://github.com/Jopyth/MMM-Remote-Control).

Here's the stacktrace I get from my error logs:

> [07.08.2023 16:14.24.358] [ERROR] ERROR! Could not validate main module js file.
> [07.08.2023 16:14.24.367] [ERROR] ReferenceError: HTMLElement is not defined
>     at Object.<anonymous> (/home/rpi/MagicMirror/modules/MMM-CalendarExt3/MMM-CalendarExt3.js:1:26)
>     at Module._compile (node:internal/modules/cjs/loader:1269:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
>     at Module.load (node:internal/modules/cjs/loader:1124:32)
>     at Module._load (node:internal/modules/cjs/loader:965:12)
>     at f._load (node:electron/js2c/asar_bundle:2:13330)
>     at Module.require (node:internal/modules/cjs/loader:1148:19)
>     at require (node:internal/modules/cjs/helpers:110:18)
>     at Class.loadModuleDefaultConfig (/home/rpi/MagicMirror/modules/MMM-Remote-Control/node_helper.js:313:30)
>     at /home/rpi/MagicMirror/modules/MMM-Remote-Control/node_helper.js:267:26
>     at FSReqCallback.oncomplete (node:fs:209:5)

    
Not sure what it triggers or not, both `CalendarExt3` and `RemoteControl` modules seem to work fine despite the error.

The only issue I noticed is some events not dimming when adjusting the brightness from the slider of the remote control page (http://{MagicMirror-address}/remote.html#edit-menu), but this may be unrelated.

I'm running MagicMirror on a Raspberry Pi 3, with Raspberry Pi OS with Desktop (Debian 11 bullseye).

**Comment by y0m1g** [comment]
I'm using the Chromium browser that ships with Raspberry Pi OS, which is at version 113.
So I suppose the message will be gone once it's updated, thank you!

**Comment by y0m1g** [comment]
Confirmed fixed with Chromium 116 🙂
